version: '3.6'
services:
  localtunnel:
    build:
      context: .
    image: localtunnel-server:latest
    container_name: "localtunnel"
    network_mode: "host"
    command: "--port 80 --domain $DOMAIN"
    restart: "always"
